[package]
name = "rice-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
console = "0.16.2"
dialoguer = "0.12.0"
reqwest = { version = "0.13.1", features = ["json"] }
tokio = { version = "1.49.0", features = ["full"] }
